model_type: gr00t_n1
dataset_path: /PATH/TO/YOUR/DATA/Sweep/
num_gpus: 1
batch_size: 16
output_dir: Checkpoints/runs/debug-gr00t-n1
max_steps: 10000
tune_visual: True
tune_llm: True
save_steps: 10000
data_config: sweep
video_backend: decord
report_to: wandb
gradient_accumulation_steps: 8
base_model_path: nvidia/GR00T-N1-2B